
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: john
  password: 123QWEasd

development:
  <<: *default
  database: msduyentoyota_development

test:
  <<: *default
  database: msduyentoyota_test

production:
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: 123QWEasd
  database: msduyentoyota
